name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-app
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: test-app
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test -- --watchAll=false
